### ISSUE TITLE
Custom signatures for the database

### ISSUE THREAD

**Issue by Benji377** [Raspirus/signatures#2]
**Is your feature request related to a problem? Please describe.**
After some research, looking for new scanning methods (#281), I found out that using signatures is still the best option we have from a speed and resource-usage point. As of right now, we are only using signatures from the Virusshare website. This is fine, but I think we could have many more signatures from other sources too. Furthermore, the Virusshare website never cleans their signatures collection, and it's therefore full of false-positives and doubles. 

**Describe the solution you'd like**
To allow users to report malware signatures or false-positives and let us organize the signatures database better, I think we need a central place where we collect and store signatures using some specific rules and scripts. Since I have a very low budget and can't currently keep a server in operation 24/7 with such a big quantity of signatures, I think putting them in a GitHub repository would be the best. This would even allow us to leverage the GitHub API to check for updates to the database and notify the user. 

**Describe alternatives you've considered**
In the future, it's surely a good and wise option to move to a dedicated server. At least to take off some load from GitHub.

**Additional context**
The GitHub repository has already been created, and its structure defined. @zja203 is working on the Python script
- REPO: https://github.com/Raspirus/signatures

**Comment by Benji377** [comment]
An interesting solution to this problem would be hosting a database somewhere online and have scripts to manipulate that data here on GitHub. The issue would be finding the correct hosting site

**Comment by GamingGuy003** [comment]
This has been mostly implemented now. For the report users can submit pull requests to the patches file in our signatures Repository. This should allow them to remove and also add hashes to our collection. In theory this issue could be closed @Benji377

**Comment by Benji377** [comment]
Perfect. Well done!
