### ISSUE TITLE
List of false positives MD5 signatures

### ISSUE THREAD

**Issue by Benji377** [Raspirus/signatures#3]
Here is a list of all the reported false positives:
- 7dea362b3fac8e00956a4952a3d4f474 (Blank files)

\
\
**Note:** This is more of a reminder than anything else, and I will try to remove all the signatures listed above on each update

**Comment by GamingGuy003** [comment]
d41d8cd98f00b204e9800998ecf8427e - empty .txt file

**Comment by Benji377** [comment]
Added false positives to README
